// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transform.proto

package transform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Response struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type ExpandReq struct {
	Shorten              string   `protobuf:"bytes,1,opt,name=shorten,proto3" json:"shorten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpandReq) Reset()         { *m = ExpandReq{} }
func (m *ExpandReq) String() string { return proto.CompactTextString(m) }
func (*ExpandReq) ProtoMessage()    {}
func (*ExpandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{2}
}

func (m *ExpandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandReq.Unmarshal(m, b)
}
func (m *ExpandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandReq.Marshal(b, m, deterministic)
}
func (m *ExpandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandReq.Merge(m, src)
}
func (m *ExpandReq) XXX_Size() int {
	return xxx_messageInfo_ExpandReq.Size(m)
}
func (m *ExpandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandReq proto.InternalMessageInfo

func (m *ExpandReq) GetShorten() string {
	if m != nil {
		return m.Shorten
	}
	return ""
}

type ExpandResp struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpandResp) Reset()         { *m = ExpandResp{} }
func (m *ExpandResp) String() string { return proto.CompactTextString(m) }
func (*ExpandResp) ProtoMessage()    {}
func (*ExpandResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{3}
}

func (m *ExpandResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandResp.Unmarshal(m, b)
}
func (m *ExpandResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandResp.Marshal(b, m, deterministic)
}
func (m *ExpandResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandResp.Merge(m, src)
}
func (m *ExpandResp) XXX_Size() int {
	return xxx_messageInfo_ExpandResp.Size(m)
}
func (m *ExpandResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandResp proto.InternalMessageInfo

func (m *ExpandResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortenReq struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenReq) Reset()         { *m = ShortenReq{} }
func (m *ShortenReq) String() string { return proto.CompactTextString(m) }
func (*ShortenReq) ProtoMessage()    {}
func (*ShortenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{4}
}

func (m *ShortenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenReq.Unmarshal(m, b)
}
func (m *ShortenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenReq.Marshal(b, m, deterministic)
}
func (m *ShortenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenReq.Merge(m, src)
}
func (m *ShortenReq) XXX_Size() int {
	return xxx_messageInfo_ShortenReq.Size(m)
}
func (m *ShortenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenReq proto.InternalMessageInfo

func (m *ShortenReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortenResp struct {
	Shorten              string   `protobuf:"bytes,1,opt,name=shorten,proto3" json:"shorten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenResp) Reset()         { *m = ShortenResp{} }
func (m *ShortenResp) String() string { return proto.CompactTextString(m) }
func (*ShortenResp) ProtoMessage()    {}
func (*ShortenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4a498eeb2ba07d, []int{5}
}

func (m *ShortenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenResp.Unmarshal(m, b)
}
func (m *ShortenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenResp.Marshal(b, m, deterministic)
}
func (m *ShortenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenResp.Merge(m, src)
}
func (m *ShortenResp) XXX_Size() int {
	return xxx_messageInfo_ShortenResp.Size(m)
}
func (m *ShortenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenResp proto.InternalMessageInfo

func (m *ShortenResp) GetShorten() string {
	if m != nil {
		return m.Shorten
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "transform.Request")
	proto.RegisterType((*Response)(nil), "transform.Response")
	proto.RegisterType((*ExpandReq)(nil), "transform.expandReq")
	proto.RegisterType((*ExpandResp)(nil), "transform.expandResp")
	proto.RegisterType((*ShortenReq)(nil), "transform.shortenReq")
	proto.RegisterType((*ShortenResp)(nil), "transform.shortenResp")
}

func init() { proto.RegisterFile("transform.proto", fileDescriptor_cb4a498eeb2ba07d) }

var fileDescriptor_cb4a498eeb2ba07d = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xef, 0x4a, 0x86, 0x30,
	0x14, 0xc6, 0x91, 0x44, 0xdb, 0xe9, 0x43, 0x71, 0xfa, 0x83, 0x08, 0x49, 0x0c, 0xa2, 0x3e, 0x19,
	0x14, 0x41, 0x97, 0x11, 0xa3, 0x1b, 0x30, 0x5a, 0x26, 0xd4, 0x76, 0xdc, 0x99, 0xd0, 0x4d, 0x75,
	0x8f, 0xa1, 0xcd, 0x69, 0xbc, 0xbe, 0xdf, 0x8e, 0xcf, 0xef, 0xc1, 0x9d, 0xdf, 0x06, 0xc7, 0xde,
	0x35, 0x86, 0xdf, 0xad, 0xfb, 0xaa, 0xc9, 0x59, 0x6f, 0x51, 0xc4, 0x40, 0x5e, 0x42, 0xae, 0x74,
	0x3f, 0x68, 0xf6, 0x88, 0x90, 0x52, 0x67, 0xda, 0x22, 0xb9, 0x4a, 0x6e, 0x85, 0x9a, 0x66, 0x59,
	0xc1, 0xa1, 0xd2, 0x4c, 0xd6, 0xb0, 0x9e, 0xb8, 0x5d, 0x71, 0x6b, 0x5a, 0x79, 0x0d, 0x42, 0x7f,
	0x53, 0x63, 0xde, 0x94, 0xee, 0xb1, 0x80, 0x9c, 0x3f, 0xac, 0xf3, 0xda, 0x84, 0xce, 0xfc, 0x29,
	0x2b, 0x80, 0xb9, 0xc6, 0x84, 0x27, 0x70, 0x30, 0xb8, 0xcf, 0xd0, 0x19, 0xc7, 0x91, 0x87, 0xea,
	0xf8, 0x9f, 0x5d, 0x7e, 0x03, 0x47, 0x91, 0x33, 0xed, 0x3f, 0xe8, 0xfe, 0x27, 0x01, 0xf1, 0x32,
	0xcb, 0xe1, 0x1d, 0xa4, 0xcf, 0x9d, 0x69, 0x11, 0xeb, 0xe5, 0x06, 0x82, 0x6d, 0x79, 0xfa, 0x2f,
	0x0b, 0x8a, 0x8f, 0x90, 0xfd, 0xed, 0x89, 0x67, 0x2b, 0x1c, 0x0d, 0xcb, 0xf3, 0x8d, 0x94, 0x09,
	0x9f, 0xe2, 0x3e, 0xb8, 0x6e, 0x2c, 0x4a, 0xe5, 0xc5, 0x56, 0xcc, 0xf4, 0x9a, 0x4d, 0x0f, 0xf2,
	0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xab, 0x25, 0x15, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransformClient is the client API for Transform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransformClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error)
	Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error)
}

type transformClient struct {
	cc *grpc.ClientConn
}

func NewTransformClient(cc *grpc.ClientConn) TransformClient {
	return &transformClient{cc}
}

func (c *transformClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/transform.Transform/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformClient) Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error) {
	out := new(ExpandResp)
	err := c.cc.Invoke(ctx, "/transform.Transform/expand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformClient) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error) {
	out := new(ShortenResp)
	err := c.cc.Invoke(ctx, "/transform.Transform/shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransformServer is the server API for Transform service.
type TransformServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Expand(context.Context, *ExpandReq) (*ExpandResp, error)
	Shorten(context.Context, *ShortenReq) (*ShortenResp, error)
}

// UnimplementedTransformServer can be embedded to have forward compatible implementations.
type UnimplementedTransformServer struct {
}

func (*UnimplementedTransformServer) Ping(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedTransformServer) Expand(ctx context.Context, req *ExpandReq) (*ExpandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expand not implemented")
}
func (*UnimplementedTransformServer) Shorten(ctx context.Context, req *ShortenReq) (*ShortenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}

func RegisterTransformServer(s *grpc.Server, srv TransformServer) {
	s.RegisterService(&_Transform_serviceDesc, srv)
}

func _Transform_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transform.Transform/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transform_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transform.Transform/Expand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServer).Expand(ctx, req.(*ExpandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transform_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transform.Transform/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServer).Shorten(ctx, req.(*ShortenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transform.Transform",
	HandlerType: (*TransformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Transform_Ping_Handler,
		},
		{
			MethodName: "expand",
			Handler:    _Transform_Expand_Handler,
		},
		{
			MethodName: "shorten",
			Handler:    _Transform_Shorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transform.proto",
}
